mydata <- read.table("household_power_consumption.txt",sep=";", header=T, stringsAsFactors=FALSE)
subdata <- subset(mydata, Date=="1/2/2007" | Date=="2/2/2007")
gap <- as(subdata[,3],"numeric")
datetime <- paste(subdata[,1],subdata[,2],sep=" ")
datetime2 <- strptime(datetime, "%d/%m/%Y%n%T")
png(file="plot3.png",width=480,heigh=480)
plot(datetime2,esm1,type="n",xlab="",ylab="Energy sub metering")
lines(datetime2,esm1,type="l")
lines(datetime2,esm2,type="l",col="red")
lines(datetime2,esm3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.off()