mydata <- read.table("household_power_consumption.txt",sep=";", header=T, stringsAsFactors=FALSE)
subdata <- subset(mydata, Date=="1/2/2007" | Date=="2/2/2007")
gap <- as(subdata[,3],"numeric")
voltage <- as(subdata[,5],"numeric")
grp <- as(subdata[,4],"numeric")
png(file="plot4.png",width=480,heigh=480)
par(mfrow = c(2,2))
hist(gap, main="Global Active Power", col = "red", xlab="Global Active Power (kilowatts)")
par(mfrow = c(2,2))
plot(datetime2,gap,type="l",xlab="",ylab="Global Active Power (kilowatts)")
par(mfrow = c(2,2))
plot(datetime2,gap,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(datetime2,voltage,type="l",xlab="datetime",ylab="Voltage")
plot(datetime2,esm1,type="n",xlab="",ylab="Energy sub metering")
lines(datetime2,esm1,type="l")
lines(datetime2,esm2,type="l",col="red")
lines(datetime2,esm3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
plot(datetime2,grp,type="l",xlab="",ylab="Global_reactive_power")
dev.off()
